[project]
name = "monolog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.6.0",
    "debugpy>=1.8.19",
    "django>=6.0",
    "pandas>=2.3.3",
]
